name: Platform as a Service (PaaS)
# run-name: ${{ github.actor }} triggered a CI job 🚀
on: [push]
jobs:
  PaaS-Start-Up-Information:
    runs-on: ubuntu-latest
    steps:
      # - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      # - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      # - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - run: echo "🍏 This job's status is ${{ job.status }}."

  PaaS-Lint-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Lint Helm
        run: |
          if [ -f "helm/Chart.yaml" ]; then
            echo "File exists"
            helm lint helm
            # Add steps to run when the file exists
          else
            echo "File does not exist"
            # Add steps to run when the file does not exist
          fi
      # - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      # - name: List files in the repository
        # run: |
        #   ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
