apiVersion: v1
kind: Namespace
metadata:
  name: paas-test-app
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paas-test-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Daniel-Perrinez/PaaS
    targetRevision: HEAD
    path: argo_dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: paas-test-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true