apiVersion: apps/v1
kind: Deployment
metadata:
  name: paas-test-app
spec:
  selector:
    matchLabels:
      app: paas-test-app
  replicas: 1
  template:
    metadata:
      labels:
        app: paas-test-app
    spec:
      containers:
      - name: paas-test-app
        image: nanajanashia/argocd-app:1.2
        # image: danielperrinez/paas:latest
        ports:
        - containerPort: 8080
